/*!
 * jQCloud Plugin for jQuery
 *
 * Version 1.0.1
 *
 * Copyright 2011, Luca Ongaro
 * Licensed under the MIT license.
 *
 * Date: Mon Aug 06 14:42:40 +0200 2012
*/
!function(t){"use strict";t.fn.jQCloud=function(e,n){var i=this,h=i.attr("id")||Math.floor(1e6*Math.random()).toString(36),a={width:i.width(),height:i.height(),center:{x:(n&&n.width?n.width:i.width())/2,y:(n&&n.height?n.height:i.height())/2},delayedMode:e.length>50,shape:!1,encodeURI:!0};n=t.extend(a,n||{}),i.addClass("jqcloud").width(n.width).height(n.height),"static"===i.css("position")&&i.css("position","relative");var o=function(){for(var a=function(t,e){var n=function(t,e){return Math.abs(2*t.offsetLeft+t.offsetWidth-2*e.offsetLeft-e.offsetWidth)<t.offsetWidth+e.offsetWidth&&Math.abs(2*t.offsetTop+t.offsetHeight-2*e.offsetTop-e.offsetHeight)<t.offsetHeight+e.offsetHeight?!0:!1},i=0;for(i=0;i<e.length;i++)if(n(t,e[i]))return!0;return!1},o=0;o<e.length;o++)e[o].weight=parseFloat(e[o].weight,10);e.sort(function(t,e){return t.weight<e.weight?1:t.weight>e.weight?-1:0});var r="rectangular"===n.shape?18:2,d=[],s=n.width/n.height,l=function(o,l){var f=h+"_word_"+o,c=6.28*Math.random(),g=0,u=0,p=0,w=5,m="",M="",x="";if(l.html=t.extend(l.html,{id:f}),l.html&&l.html["class"]&&(m=l.html["class"],delete l.html["class"]),e[0].weight>e[e.length-1].weight&&(w=Math.round((l.weight-e[e.length-1].weight)/(e[0].weight-e[e.length-1].weight)*9)+1),x=t("<span>").attr(l.html).addClass("w"+w+" "+m),l.link?("string"==typeof l.link&&(l.link={href:l.link}),n.encodeURI&&(l.link=t.extend(l.link,{href:encodeURI(l.link.href).replace(/'/g,"%27")})),M=t("<a>").attr(l.link).text(l.text)):M=l.text,x.append(M),l.handlers)for(var v in l.handlers)l.handlers.hasOwnProperty(v)&&"function"==typeof l.handlers[v]&&t(x).bind(v,l.handlers[v]);i.append(x);var y=x.width(),k=x.height(),R=n.center.x-y/2,b=n.center.y-k/2,C=x[0].style;for(C.position="absolute",C.left=R+"px",C.top=b+"px";a(document.getElementById(f),d);){if("rectangular"===n.shape)switch(u++,u*r>(1+Math.floor(p/2))*r*(p%4%2===0?1:s)&&(u=0,p++),p%4){case 1:R+=r*s+2*Math.random();break;case 2:b-=r+2*Math.random();break;case 3:R-=r*s+2*Math.random();break;case 0:b+=r+2*Math.random()}else g+=r,c+=(o%2===0?1:-1)*r,R=n.center.x-y/2+g*Math.cos(c)*s,b=n.center.y+g*Math.sin(c)-k/2;C.left=R+"px",C.top=b+"px"}d.push(document.getElementById(f)),t.isFunction(l.afterWordRender)&&l.afterWordRender.call(x)},f=function(h){return h=h||0,i.is(":visible")?void(h<e.length?(l(h,e[h]),setTimeout(function(){f(h+1)},10)):t.isFunction(n.afterCloudRender)&&n.afterCloudRender.call(i)):void setTimeout(function(){f(h)},10)};n.delayedMode?f():(t.each(e,l),t.isFunction(n.afterCloudRender)&&n.afterCloudRender.call(i))};return setTimeout(function(){o()},10),i}}(jQuery);